### ISSUE TITLE
I'd like to make this an official Checka11y.css Angular package

### ISSUE THREAD

**Issue by jackdomleo7** [AlaaEl-DinAhmed/ngx-checka11y#1]
Hi, I'd like to make a proposal about making this the official Angular package for Checka11y.css, however there are a few things I'd like you to consider first, and I'd like to hear your thoughts 🙂:

- I noticed you import the Checka11y.css stylesheet via JsDelivr, would you be willing instead to make this more reliable and install Checka11y.css as a dependency (not a dev dependency) - it can be found on npm [here](https://www.npmjs.com/package/checka11y-css).
- Consistent brand naming (to prevent confusion and to prove the fact that this is a supported package by Checka11y.css/me 🙂):
  - "Checka11y.css" for anything in a description, README, etc. (no capital 'A' for a11y, and a capital 'C' at the beginning)
  - "checka11y-css" or "checka11yCss" for anything in code (choose a relevant format, kebab-casing or camelCasing)
- Consider using a customised logo for your README (if I may, I'd like to send you one on Twitter or LinkedIn)
- Consider adding some relevant badges of your choice to the README from [shields.io](https://shields.io)
- Change the `a11y-tes` tag to `a11y-testing`

I'd love to hear your thoughts and actions on this. And if all goes well, I'd be happy to link to this repo/package from the Checka11y.css README and website. 🤝

**Comment by AlaaEl-DinAhmed** [comment]
Hi, it's my pleasure to make the package the official Angular package for Checka11y.css.
I will make a checklist here of all requirements and I will update it as soon as I finish one of them.

- [x] `a11y-tes tag` to be `a11y-testing`
- [x] Using Checka11y.css as  dependency not a dev dependency.
- [x] `Checka11y.css` for anything in a description, README, etc
- [x] Consistent brand naming to be camelCase.
- [x] Adding some relevant badges to the README
- [x] Using a customised logo for your README
